# Generated by Django 5.0 on 2023-12-31 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('pays', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('classe_id', models.AutoField(primary_key=True, serialize=False)),
                ('classe_name', models.CharField(max_length=255)),
                ('classe_niveau', models.CharField(max_length=50)),
                ('effectif', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('domaine_id', models.AutoField(primary_key=True, serialize=False)),
                ('domaine_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Editeur',
            fields=[
                ('editeur_id', models.AutoField(primary_key=True, serialize=False)),
                ('editeur_name', models.CharField(max_length=255)),
                ('pays', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ECUE',
            fields=[
                ('ecue_id', models.AutoField(primary_key=True, serialize=False)),
                ('ecue_name', models.CharField(max_length=255)),
                ('classe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('matricule', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('classe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.classe')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exemplaire',
            fields=[
                ('exemplaire_id', models.AutoField(primary_key=True, serialize=False)),
                ('exemplaire_number', models.IntegerField()),
                ('edition_number', models.IntegerField()),
                ('etat', models.CharField(max_length=255)),
                ('disponible', models.BooleanField(default=True)),
                ('editeur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.editeur')),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('emprunt_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_emprunt', models.DateTimeField()),
                ('delais', models.IntegerField()),
                ('date_remise', models.DateTimeField()),
                ('etat_remise', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exemplaire_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.exemplaire')),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('livre_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=20)),
                ('publication_date', models.DateField()),
                ('language', models.CharField(max_length=50)),
                ('nb_page', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Qte_stock', models.IntegerField()),
                ('domaine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.domaine')),
            ],
        ),
        migrations.AddField(
            model_name='exemplaire',
            name='livre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.livre'),
        ),
        migrations.CreateModel(
            name='LivreECUE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.ecue')),
                ('livre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.livre')),
            ],
        ),
    ]
