# Generated by Django 5.0 on 2024-01-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_auteur_classe_domaine_editeur_ecue_etudiant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='livre_images/'),
        ),
    ]
